server:
  port: 8080

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        generate_statistics: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:liquibase/db.changelog-master.xml
    drop-first: ${DB_DROP_FIRST:false}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5421/parking-service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    hikari:
      maximum-pool-size: 10

management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: metrics
      exposure:
        include: health,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

price-list:
  price-rates:
    - type: STUDENT
      price: 15
    - type: STAFF
      price: 20
    - type: GUEST
      price: 25
