{
 "title": "parking-service dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Errors number", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of 5xx responses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{ status=~\"5.*\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Response time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "PlaceController GET /place/free/{id}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_max{method=\"GET\", uri=\"/place/free/{id}\"}[$__rate_interval]))",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"GET\", uri=\"/place/free/{id}\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "PlaceController GET /place/free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_max{method=\"GET\", uri=\"/place/free\"}[$__rate_interval]))",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"GET\", uri=\"/place/free\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "StatisticsController GET /statistics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_max{method=\"GET\", uri=\"/statistics\"}[$__rate_interval]))",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"GET\", uri=\"/statistics\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "PlaceController POST /place/book",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_max{method=\"POST\", uri=\"/place/book\"}[$__rate_interval]))",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"POST\", uri=\"/place/book\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "PlaceController POST /place/unbook/{id}",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_max{method=\"POST\", uri=\"/place/unbook/{id}\"}[$__rate_interval]))",
     "legendFormat": "response time"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{method=\"POST\", uri=\"/place/unbook/{id}\"}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  }
 ]
}